// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"bff/handler"
	"bff/infra"
	"bff/usecase"
)

// Injectors from wire.go:

func InitUserHandler() *handler.UserHandler {
	api := infra.NewApi()
	userUsecase := usecase.NewUserUsecase(api)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}

func InitSystemHandler() *handler.SystemHandler {
	systemHandler := handler.NewSystemHandler()
	return systemHandler
}
