// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"bff/handler"
	"bff/infra"
	"bff/usecase"
)

// Injectors from wire.go:

func InitUserUsecase() usecase.UserUsecase {
	api := infra.NewApi()
	userUsecase := usecase.NewUserUsecase(api)
	return userUsecase
}

func InitUserHandler() handler.UserHandler {
	api := infra.NewApi()
	userUsecase := usecase.NewUserUsecase(api)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}

// wire.go:

func InitSystemHandler() handler.SystemHandler {
	return handler.SystemHandler{}
}
